@host = http://127.0.0.1:{{$dotenv PORT}}
@sessionCookie = REPLACE_THIS_WITH_SESSION_COOKIE

# /users ENDPOINTS
# Register endpoint
POST {{host}}/users/register
Content-Type: application/json
Set-Cookie: {{sessionCookie}}

{
   "name": "",
   "email": "",
   "username": "",
   "password": ""
}

###

# Login endpoint
POST {{host}}/users/login
Content-Type: application/json
Set-Cookie: {{sessionCookie}}

{
   "username": "",
   "password": ""
}

###

# Logout endpoint
GET {{host}}/users/logout
Set-Cookie: {{sessionCookie}}

###

# View current logged in user profile endpoint
GET {{host}}/users/profile
Set-Cookie: {{sessionCookie}}

###

# View specific user profile endpoint
GET {{host}}/users/profile/:username

###

# View all user profiles endpoint
GET {{host}}/users

###

# Update current logged in user profile endpoint
PATCH {{host}}/users/profile/update
Content-Type: application/json
Set-Cookie: {{sessionCookie}}

{
   "name": "",
   "email": "",
   "username": ""
}

###

# Change current logged in user password endpoint
PATCH {{host}}/users/profile/update/password
Content-Type: application/json
Set-Cookie: {{sessionCookie}}

{
   "password": ""
}

###

# Delete current logged in user endpoint
DELETE {{host}}/users/profile/delete
Set-Cookie: {{sessionCookie}}

###

# /admin ENDPOINTS
# Create user endpoint
POST {{host}}/admin/create
Content-Type: application/json
Set-Cookie: {{sessionCookie}}

{
   "role": 4,
   "name": "",
   "email": "",
   "username": "",
   "password": ""
}

###

# View specific user profile endpoint
GET {{host}}/admin/view/:username
Set-Cookie: {{sessionCookie}}

###

# View all user profiles endpoint
GET {{host}}/admin/view
Set-Cookie: {{sessionCookie}}

###

# Update specific user profile endpoint
PATCH {{host}}/admin/update/:username
Content-Type: application/json
Set-Cookie: {{sessionCookie}}

{
   "role": 4,
   "name": "",
   "email": "",
   "username": ""
}

###

# Change specific user password endpoint
PATCH {{host}}/admin/update/password/:username
Content-Type: application/json
Set-Cookie: {{sessionCookie}}

{
   "password": ""
}

###

# Delete specific user endpoint
DELETE {{host}}/admin/delete/:username
Set-Cookie: {{sessionCookie}}
